import { Link } from "react-router-dom";

const S = {
  wrap: { background: "#08080f", minHeight: "100vh", color: "#e0eaf5", fontFamily: "-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif" },
  nav: { borderBottom: "1px solid #0d1b2a", padding: "0 24px", display: "flex", alignItems: "center", height: 56, background: "#050a14" },
  brand: { fontWeight: 800, fontSize: 18, color: "#e0eaf5" },
  inner: { maxWidth: 720, margin: "0 auto", padding: "56px 24px 80px" },
  h1: { fontSize: 32, fontWeight: 800, letterSpacing: "-0.02em", marginBottom: 8, color: "#e0eaf5" },
  meta: { fontSize: 13, color: "#4a6a8a", marginBottom: 48 },
  h2: { fontSize: 18, fontWeight: 700, color: "#e0eaf5", margin: "36px 0 12px" },
  p: { fontSize: 14, color: "#8a9ab8", lineHeight: 1.9, margin: "0 0 16px" },
  footer: { borderTop: "1px solid #0d1b2a", padding: "20px 24px", textAlign: "center", fontSize: 12, color: "#4a6a8a" },
};

export default function TermsOfService() {
  return (
    <div style={S.wrap}>
      <nav style={S.nav}>
        <Link to="/" style={S.brand}>async<span style={{ color: "#4f46e5" }}>-mode</span></Link>
        <div style={{ flex: 1 }} />
        <Link to="/" style={{ fontSize: 13, color: "#4a6a8a" }}>← Back to home</Link>
      </nav>
      <div style={S.inner}>
        <h1 style={S.h1}>Terms of Service</h1>
        <p style={S.meta}>Last updated: June 2026 · async-mode.com</p>

        <p style={S.p}>By accessing or using async-mode.com ("the Platform"), you agree to be bound by these Terms of Service. Please read them carefully.</p>

        <h2 style={S.h2}>1. Acceptance of Terms</h2>
        <p style={S.p}>By creating an account or using any part of the Platform, you confirm that you are at least 16 years old and that you have read, understood, and agree to these Terms. If you use the Platform on behalf of an organization, you represent that you have authority to bind that organization to these Terms.</p>

        <h2 style={S.h2}>2. Description of Service</h2>
        <p style={S.p}>async-mode.com provides an AI-powered video automation platform that generates scripts, voice narration, visuals, captions, and publishes content to connected platforms. The service is provided "as-is" and may be modified or discontinued at any time.</p>

        <h2 style={S.h2}>3. Account Registration</h2>
        <p style={S.p}>Accounts are manually reviewed and approved. You are responsible for maintaining the confidentiality of your account credentials. You must notify us immediately of any unauthorized use. We reserve the right to refuse service or terminate accounts at our discretion.</p>

        <h2 style={S.h2}>4. Acceptable Use</h2>
        <p style={S.p}>You agree NOT to use the Platform to:</p>
        <p style={S.p}>• Generate content that is illegal, harmful, defamatory, harassing, or violates the rights of others<br />
        • Produce misinformation, deepfakes intended to deceive, or impersonation content<br />
        • Violate the terms of service of YouTube, TikTok, Spotify, or any connected platform<br />
        • Reverse-engineer, scrape, or attempt to extract the underlying models or systems<br />
        • Circumvent usage limits, trial restrictions, or billing systems<br />
        • Upload copyrighted material you do not have rights to use</p>

        <h2 style={S.h2}>5. AI-Generated Content</h2>
        <p style={S.p}>Content generated by the Platform may be imperfect, inaccurate, or unsuitable for your purposes. All generated videos are uploaded to YouTube as private drafts — you are responsible for reviewing content before making it public. We are not responsible for the accuracy, completeness, or legality of AI-generated content.</p>

        <h2 style={S.h2}>6. Intellectual Property</h2>
        <p style={S.p}>Content you submit (topics, scripts, branding) remains your property. Content generated by the Platform using your inputs is yours to use, subject to the licenses of underlying AI models and stock footage providers. The Platform itself, including its code, design, and proprietary algorithms, remains the intellectual property of async-mode.com.</p>

        <h2 style={S.h2}>7. Payment & Subscriptions</h2>
        <p style={S.p}>Paid plans are billed monthly in USD. Your subscription renews automatically unless cancelled. You may cancel at any time from your account settings — access continues until the end of the billing period. See our <Link to="/refund" style={{ color: "#818cf8" }}>Refund Policy</Link> for refund terms.</p>

        <h2 style={S.h2}>8. Trial Accounts</h2>
        <p style={S.p}>Trial accounts receive limited access (2 videos, 24 hours) to evaluate the Platform. Trial credits are non-transferable and expire at the end of the trial period. We reserve the right to modify or discontinue the trial offering at any time.</p>

        <h2 style={S.h2}>9. Limitation of Liability</h2>
        <p style={S.p}>To the fullest extent permitted by law, async-mode.com shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Platform. Our total liability for any claim shall not exceed the amount you paid us in the 3 months preceding the claim.</p>

        <h2 style={S.h2}>10. Disclaimers</h2>
        <p style={S.p}>The Platform is provided "as is" without warranties of any kind. We do not guarantee that the service will be uninterrupted, error-free, or that generated content will meet your requirements. We are not responsible for actions taken by connected third-party platforms (YouTube, Spotify, etc.).</p>

        <h2 style={S.h2}>11. Termination</h2>
        <p style={S.p}>We may suspend or terminate your account if you violate these Terms, engage in fraudulent activity, or for any reason at our sole discretion. Upon termination, your right to use the Platform ceases immediately. We will retain data per our Privacy Policy.</p>

        <h2 style={S.h2}>12. Governing Law</h2>
        <p style={S.p}>These Terms are governed by applicable law. Disputes shall first be attempted to be resolved through good-faith negotiation. If unresolved, disputes shall be submitted to binding arbitration.</p>

        <h2 style={S.h2}>13. Changes to Terms</h2>
        <p style={S.p}>We may update these Terms at any time. We'll notify you by email or platform notice at least 7 days before changes take effect. Continued use after that date constitutes acceptance of the updated Terms.</p>

        <h2 style={S.h2}>14. Contact</h2>
        <p style={S.p}>Questions about these Terms? Contact us at <a href="mailto:help@async-mode.com" style={{ color: "#818cf8" }}>help@async-mode.com</a>.</p>
      </div>
      <footer style={S.footer}>
        <Link to="/privacy" style={{ color: "#4a6a8a", marginRight: 16 }}>Privacy Policy</Link>
        <Link to="/refund" style={{ color: "#4a6a8a", marginRight: 16 }}>Refund Policy</Link>
        <Link to="/cookies" style={{ color: "#4a6a8a", marginRight: 16 }}>Cookie Policy</Link>
        <Link to="/" style={{ color: "#4a6a8a" }}>← Home</Link>
      </footer>
    </div>
  );
}
