const CURRENT_DATE = new Date().toLocaleDateString("en-GB", {
  day: "numeric", month: "long", year: "numeric",
});

const SECTIONS = [
  {
    title: "1. Acceptance of Terms",
    body: `By accessing or using the 4Life Mystery platform ("Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.`,
  },
  {
    title: "2. Description of Service",
    body: `4Life Mystery is an automated content creation and distribution platform that generates, schedules, and publishes video content to third-party platforms including YouTube and TikTok. The Service uses artificial intelligence to produce scripts, voiceovers, visuals, and captions.`,
  },
  {
    title: "3. Platform Compliance",
    body: `All content published through this Service is subject to the terms and community guidelines of the destination platforms (YouTube, TikTok, etc.). We are committed to complying with all applicable platform policies, including:\n• YouTube Terms of Service: https://www.youtube.com/t/terms\n• TikTok Terms of Service: https://www.tiktok.com/legal/page/row/terms-of-service/en\nUsers are responsible for ensuring content published via the Service does not violate any applicable laws or platform guidelines.`,
  },
  {
    title: "4. Intellectual Property",
    body: `Content generated by the Service is owned by the operator of the platform account to which it is published. We do not claim ownership of AI-generated content produced on your behalf. You retain all rights to your channel, account, and published content.`,
  },
  {
    title: "5. Third-Party APIs and Quotas",
    body: `The Service relies on third-party APIs (YouTube Data API, TikTok Content Posting API, ElevenLabs, Groq, Pexels, etc.). We are not responsible for outages, quota limits, or policy changes imposed by these third-party providers. API usage is subject to each provider's terms and daily quotas.`,
  },
  {
    title: "6. Automated Publishing",
    body: `The Service may automatically generate and publish content on a scheduled basis. You are responsible for reviewing published content and for any consequences arising from automated publication. You may disable automation at any time through the Service settings.`,
  },
  {
    title: "7. Limitation of Liability",
    body: `The Service is provided "as is" without warranties of any kind. We shall not be liable for any indirect, incidental, or consequential damages arising from:\n• Content removed or penalised by third-party platforms\n• API quota exhaustion or third-party service outages\n• Inaccuracies in AI-generated content\n• Loss of revenue or channel monetisation`,
  },
  {
    title: "8. Modifications",
    body: `We reserve the right to modify these Terms of Service at any time. Changes take effect upon posting to this page. Continued use of the Service after changes are posted constitutes acceptance of the revised terms.`,
  },
  {
    title: "9. Termination",
    body: `We reserve the right to suspend or terminate access to the Service at our discretion, including for violation of these terms or applicable platform policies.`,
  },
  {
    title: "10. Contact",
    body: `For questions about these Terms of Service, contact us at: support@4lifemystery.com`,
  },
];

export default function TermsOfService() {
  return (
    <div style={{
      position: "fixed",
      inset: 0,
      overflowY: "auto",
      background: "#07080f",
      color: "#cdd8e8",
      fontFamily: "'DM Mono', 'Fira Code', monospace",
      WebkitFontSmoothing: "antialiased",
    }}>
      {/* ── Nav ── */}
      <nav style={{
        position: "sticky",
        top: 0,
        zIndex: 10,
        background: "rgba(7,8,15,0.92)",
        backdropFilter: "blur(12px)",
        borderBottom: "1px solid #12233a",
        padding: "0 24px",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        height: 52,
      }}>
        <a href="https://4lifemystery.com/" style={{ textDecoration: "none", display: "flex", alignItems: "center", gap: 8 }}>
          <span style={{
            fontFamily: "sans-serif",
            fontWeight: 800,
            fontSize: 17,
            background: "linear-gradient(135deg,#00b4ff,#00e080)",
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
          }}>4LIFE</span>
          <span style={{ fontFamily: "sans-serif", fontWeight: 800, fontSize: 17, color: "#cdd8e8" }}>MYSTERY</span>
        </a>
        <div style={{ display: "flex", gap: 20, alignItems: "center" }}>
          <a href="https://4lifemystery.com/" style={{ fontSize: 11, color: "#5a7a9a", textDecoration: "none", letterSpacing: "0.08em" }}
            onMouseEnter={e => e.target.style.color = "#00b4ff"} onMouseLeave={e => e.target.style.color = "#5a7a9a"}>
            ← Home
          </a>
          <a href="/privacy-policy" style={{ fontSize: 11, color: "#5a7a9a", textDecoration: "none", letterSpacing: "0.08em" }}
            onMouseEnter={e => e.target.style.color = "#00b4ff"} onMouseLeave={e => e.target.style.color = "#5a7a9a"}>
            Privacy Policy
          </a>
        </div>
      </nav>

      {/* ── Content ── */}
      <main style={{ maxWidth: 760, margin: "0 auto", padding: "52px 24px 80px" }}>
        {/* Header */}
        <div style={{ marginBottom: 52 }}>
          <div style={{ fontSize: 10, letterSpacing: "0.2em", color: "#00a0dc", marginBottom: 14, fontFamily: "sans-serif" }}>
            4LIFE MYSTERY
          </div>
          <h1 style={{
            fontSize: 38,
            fontWeight: 800,
            margin: 0,
            color: "#e8f4ff",
            fontFamily: "sans-serif",
            letterSpacing: "-0.02em",
            lineHeight: 1.1,
          }}>
            Terms of Service
          </h1>
          <div style={{
            display: "flex",
            alignItems: "center",
            gap: 16,
            marginTop: 16,
          }}>
            <span style={{ fontSize: 12, color: "#3d5a72" }}>Last updated: {CURRENT_DATE}</span>
            <span style={{ width: 1, height: 14, background: "#12233a", display: "inline-block" }} />
            <span style={{ fontSize: 12, color: "#3d5a72" }}>Version 1.0</span>
          </div>
        </div>

        {/* Intro card */}
        <div style={{
          background: "rgba(0,160,220,0.06)",
          border: "1px solid rgba(0,160,220,0.18)",
          borderRadius: 12,
          padding: "18px 22px",
          marginBottom: 44,
          fontSize: 13,
          lineHeight: 1.8,
          color: "#7a9bb5",
        }}>
          Please read these Terms of Service carefully before using the 4Life Mystery platform. By accessing or using our Service, you acknowledge that you have read and agree to be bound by these terms.
        </div>

        {/* Sections */}
        {SECTIONS.map(({ title, body }) => (
          <div key={title} style={{
            marginBottom: 36,
            paddingBottom: 36,
            borderBottom: "1px solid #0d1e30",
          }}>
            <h2 style={{
              fontSize: 14,
              fontWeight: 700,
              color: "#e8f4ff",
              marginBottom: 12,
              fontFamily: "sans-serif",
              letterSpacing: "0.02em",
            }}>
              {title}
            </h2>
            <p style={{
              fontSize: 13,
              lineHeight: 1.9,
              color: "#7a9bb5",
              whiteSpace: "pre-line",
              margin: 0,
            }}>
              {body}
            </p>
          </div>
        ))}
      </main>

      {/* ── Footer ── */}
      <footer style={{
        borderTop: "1px solid #0d1e30",
        padding: "32px 24px",
        background: "#050608",
      }}>
        <div style={{ maxWidth: 760, margin: "0 auto" }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", flexWrap: "wrap", gap: 20 }}>
            <div>
              <div style={{ fontSize: 13, fontWeight: 700, color: "#cdd8e8", fontFamily: "sans-serif", marginBottom: 6 }}>4Life Mystery</div>
              <div style={{ fontSize: 11, color: "#3d5a72" }}>© {new Date().getFullYear()} 4Life Mystery. All rights reserved.</div>
              <div style={{ fontSize: 11, color: "#3d5a72", marginTop: 4 }}>{CURRENT_DATE}</div>
            </div>
            <div style={{ display: "flex", gap: 20, alignItems: "center", flexWrap: "wrap" }}>
              <a href="https://www.youtube.com/@4lifemystery" target="_blank" rel="noreferrer" style={{
                display: "flex", alignItems: "center", gap: 6,
                fontSize: 11, color: "#5a7a9a", textDecoration: "none",
                padding: "6px 12px", borderRadius: 7, border: "1px solid #12233a",
                transition: "all 0.15s",
              }}
                onMouseEnter={e => { e.currentTarget.style.borderColor = "#ff0000"; e.currentTarget.style.color = "#ff0000"; }}
                onMouseLeave={e => { e.currentTarget.style.borderColor = "#12233a"; e.currentTarget.style.color = "#5a7a9a"; }}>
                ▶ YouTube
              </a>
              <a href="https://www.tiktok.com/@4lifemystery" target="_blank" rel="noreferrer" style={{
                display: "flex", alignItems: "center", gap: 6,
                fontSize: 11, color: "#5a7a9a", textDecoration: "none",
                padding: "6px 12px", borderRadius: 7, border: "1px solid #12233a",
                transition: "all 0.15s",
              }}
                onMouseEnter={e => { e.currentTarget.style.borderColor = "#ff2d55"; e.currentTarget.style.color = "#ff2d55"; }}
                onMouseLeave={e => { e.currentTarget.style.borderColor = "#12233a"; e.currentTarget.style.color = "#5a7a9a"; }}>
                ♪ TikTok
              </a>
              <a href="/privacy-policy" style={{ fontSize: 11, color: "#3d5a72", textDecoration: "none" }}
                onMouseEnter={e => e.target.style.color = "#00b4ff"} onMouseLeave={e => e.target.style.color = "#3d5a72"}>
                Privacy Policy
              </a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
