export default function TermsOfService() {
  return (
    <div style={{
      minHeight: "100vh",
      background: "#08080f",
      color: "#e0e0e0",
      fontFamily: "'Inter', sans-serif",
      padding: "60px 24px",
    }}>
      <div style={{ maxWidth: 760, margin: "0 auto" }}>
        <div style={{ marginBottom: 48 }}>
          <div style={{ fontSize: 11, letterSpacing: "0.15em", color: "#00a0dc", marginBottom: 12 }}>
            4LIFE MYSTERY
          </div>
          <h1 style={{ fontSize: 36, fontWeight: 800, margin: 0, color: "#fff" }}>
            Terms of Service
          </h1>
          <p style={{ color: "#666", marginTop: 10, fontSize: 13 }}>
            Last updated: March 2026
          </p>
        </div>

        {[
          {
            title: "1. Acceptance of Terms",
            body: `By accessing or using the 4Life Mystery platform ("Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.`,
          },
          {
            title: "2. Description of Service",
            body: `4Life Mystery is an automated content creation and distribution platform that generates, schedules, and publishes video content to third-party platforms including YouTube and TikTok. The Service uses artificial intelligence to produce scripts, voiceovers, visuals, and captions.`,
          },
          {
            title: "3. Platform Compliance",
            body: `All content published through this Service is subject to the terms and community guidelines of the destination platforms (YouTube, TikTok, etc.). We are committed to complying with all applicable platform policies, including:
• YouTube Terms of Service: https://www.youtube.com/t/terms
• TikTok Terms of Service: https://www.tiktok.com/legal/page/row/terms-of-service/en
Users are responsible for ensuring content published via the Service does not violate any applicable laws or platform guidelines.`,
          },
          {
            title: "4. Intellectual Property",
            body: `Content generated by the Service is owned by the operator of the platform account to which it is published. We do not claim ownership of AI-generated content produced on your behalf. You retain all rights to your channel, account, and published content.`,
          },
          {
            title: "5. Third-Party APIs and Quotas",
            body: `The Service relies on third-party APIs (YouTube Data API, TikTok Content Posting API, ElevenLabs, Groq, Pexels, etc.). We are not responsible for outages, quota limits, or policy changes imposed by these third-party providers. API usage is subject to each provider's terms and daily quotas.`,
          },
          {
            title: "6. Automated Publishing",
            body: `The Service may automatically generate and publish content on a scheduled basis. You are responsible for reviewing published content and for any consequences arising from automated publication. You may disable automation at any time through the Service settings.`,
          },
          {
            title: "7. Limitation of Liability",
            body: `The Service is provided "as is" without warranties of any kind. We shall not be liable for any indirect, incidental, or consequential damages arising from:
• Content removed or penalised by third-party platforms
• API quota exhaustion or third-party service outages
• Inaccuracies in AI-generated content
• Loss of revenue or channel monetisation`,
          },
          {
            title: "8. Modifications",
            body: `We reserve the right to modify these Terms of Service at any time. Changes take effect upon posting to this page. Continued use of the Service after changes are posted constitutes acceptance of the revised terms.`,
          },
          {
            title: "9. Termination",
            body: `We reserve the right to suspend or terminate access to the Service at our discretion, including for violation of these terms or applicable platform policies.`,
          },
          {
            title: "10. Contact",
            body: `For questions about these Terms of Service, contact us at: support@4lifemystery.com`,
          },
        ].map(({ title, body }) => (
          <div key={title} style={{ marginBottom: 36 }}>
            <h2 style={{ fontSize: 17, fontWeight: 700, color: "#fff", marginBottom: 10 }}>
              {title}
            </h2>
            <p style={{ fontSize: 14, lineHeight: 1.8, color: "#aaa", whiteSpace: "pre-line", margin: 0 }}>
              {body}
            </p>
          </div>
        ))}

        <div style={{
          marginTop: 60,
          paddingTop: 24,
          borderTop: "1px solid #1a1a2e",
          fontSize: 12,
          color: "#444",
        }}>
          © 2026 4Life Mystery. All rights reserved.
        </div>
      </div>
    </div>
  );
}
